export setMarkerIndex from './map/set-marker-index';
export setMarkerCoords from './map/set-marker-coords';
export setMarkerName from './set-marker-name';
export setCurrentMarker from './set-current-marker';
export setMarkerSearchIndexes from './list/set-marker-search-indexes';
export setMarkerDeleteIndex from './list/set-marker-delete-index';
export setObject from './objects/set-object';
export setObjectDeleteIndex from './objects/set-object-delete-index';
export fetchMarkers from './fetch-markers';
