version: '3'
services:
  node:
    container_name: maps_node
    image: node:7.7.4
    stdin_open: true
    tty: true
    volumes:
      - ../package.json:/app/package.json
      - ../node_modules:/app/node_modules
      - ../.babelrc:/app/.babelrc
      - ../server.config.js:/app/server.config.js
      - ../src:/app/src

  nginx:
    container_name: maps_nginx
    image: nginx:1.11
    ports:
      - 80:80
    volumes:
      - ../build:/var/www/build
      - ./nginx:/etc/nginx
      - ./logs:/etc/nginx/logs
    depends_on:
      - node
