version: '3'
services:
  client_node:
    container_name: maps_node
    image: node:7.9.0
    networks:
      - maps
    stdin_open: true
    tty: true
    volumes:
      - ../config:/config
      - ../package.json:/package.json
      - ../node_modules:/node_modules
      - ../build/server.js:/build/server.js
      - ../src:/src

  client_nginx:
    container_name: maps_nginx
    image: nginx:1.11
    networks:
      - maps
    ports:
      - 80:80
    volumes:
      - ../build:/var/www/build
      - ./nginx:/etc/nginx
      - ./logs:/etc/nginx/logs
    depends_on:
      - client_node

networks:
  maps:
    external:
      name: mapsapi_default
