version: '3'
services:
  node:
    container_name: maps_node
    image: node:7.7.4
    networks:
      - maps
    stdin_open: true
    tty: true
    volumes:
      - ../package.json:/package.json
      - ../node_modules:/node_modules
      - ../.babelrc:/.babelrc
      - ../server.config.js:/server.config.js
      - ../src:/src

  nginx:
    container_name: maps_nginx
    image: nginx:1.11
    networks:
      - maps
    ports:
      - 80:80
    volumes:
      - ../build:/var/www/build
      - ./nginx:/etc/nginx
      - ./logs:/etc/nginx/logs
    depends_on:
      - node

networks:
  maps:
    driver: bridge